[build]
builder = "nixpacks"
buildCommand = "cd my-medusa-store && pnpm install && pnpm run build"

[deploy]
startCommand = "cd my-medusa-store && medusa db:migrate && medusa start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10