services:
  - type: web
    name: strike-shop-api
    runtime: node
    region: frankfurt
    plan: starter
    rootDir: my-medusa-store
    buildCommand: npm install && npm run build && npm run predeploy
    startCommand: npm run start:render
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DISABLE_MEDUSA_ADMIN
        value: false