apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    version: 1
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceName: Prometheus
          matcherRegex: "traceID=(\\w+)"
          name: TraceID
          url: '$${__value.raw}'