global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'taskflow-staging'
    environment: 'staging'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them
rule_files:
  - '/etc/prometheus/rules/*.yml'

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  # Backend API metrics
  - job_name: 'taskflow-backend'
    static_configs:
      - targets: ['backend:8000']
        labels:
          service: 'backend'
          component: 'api'
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Nginx metrics via nginx_status
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:8080']
        labels:
          service: 'nginx'
          component: 'proxy'
    metrics_path: '/nginx_status'

  # PostgreSQL metrics (requires postgres_exporter)
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          service: 'postgresql'
          component: 'database'

  # Redis metrics (requires redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: 'redis'
          component: 'cache'

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'node'
          component: 'system'

  # Container metrics from cAdvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          service: 'cadvisor'
          component: 'containers'

  # Loki metrics
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
        labels:
          service: 'loki'
          component: 'logging'

  # Blackbox exporter for uptime monitoring
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://staging.taskflow-ai.dev
        - https://staging-api.taskflow-ai.dev
        - https://staging.taskflow-ai.dev/health
        - https://staging-api.taskflow-ai.dev/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # SSL certificate monitoring
  - job_name: 'blackbox-ssl'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://staging.taskflow-ai.dev
        - https://staging-api.taskflow-ai.dev
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'probe_ssl_earliest_cert_expiry'
        target_label: __name__
        replacement: 'ssl_cert_expiry_seconds'