services:
  - type: web
    name: medusa-backend
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: medusa-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: COOKIE_SECRET
        generateValue: true
      - key: STORE_CORS
        value: https://your-frontend.vercel.app
      - key: ADMIN_CORS
        value: https://your-frontend.vercel.app
      - key: AUTH_CORS
        value: https://your-frontend.vercel.app

databases:
  - name: medusa-db
    plan: free