groups:
  - name: application
    interval: 30s
    rules:
      # Backend API alerts
      - alert: BackendDown
        expr: up{job="backend"} == 0
        for: 5m
        labels:
          severity: critical
          service: backend
        annotations:
          summary: "Backend API is down"
          description: "The backend API at {{ $labels.instance }} has been down for more than 5 minutes."

      - alert: HighRequestLatency
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="backend"}[5m])) > 0.5
        for: 10m
        labels:
          severity: warning
          service: backend
        annotations:
          summary: "High request latency on backend"
          description: "95th percentile of HTTP requests is above 500ms (current value: {{ $value }}s)"

      - alert: HighErrorRate
        expr: rate(http_requests_total{job="backend",status=~"5.."}[5m]) > 0.05
        for: 10m
        labels:
          severity: warning
          service: backend
        annotations:
          summary: "High error rate on backend"
          description: "Error rate is above 5% (current value: {{ $value | humanizePercentage }})"

      # Database alerts
      - alert: DatabaseDown
        expr: up{job="postgres"} == 0
        for: 5m
        labels:
          severity: critical
          service: database
        annotations:
          summary: "PostgreSQL database is down"
          description: "PostgreSQL database has been down for more than 5 minutes."

      - alert: DatabaseConnectionPoolExhausted
        expr: postgresql_connections_active / postgresql_connections_max > 0.8
        for: 10m
        labels:
          severity: warning
          service: database
        annotations:
          summary: "Database connection pool near exhaustion"
          description: "Database is using {{ $value | humanizePercentage }} of maximum connections"

      # Redis alerts
      - alert: RedisDown
        expr: up{job="redis"} == 0
        for: 5m
        labels:
          severity: critical
          service: redis
        annotations:
          summary: "Redis is down"
          description: "Redis cache has been down for more than 5 minutes."

      - alert: RedisHighMemoryUsage
        expr: redis_memory_used_bytes / redis_memory_max_bytes > 0.9
        for: 10m
        labels:
          severity: warning
          service: redis
        annotations:
          summary: "Redis memory usage is high"
          description: "Redis is using {{ $value | humanizePercentage }} of maximum memory"

      # Celery alerts
      - alert: CeleryWorkerDown
        expr: flower_worker_online == 0
        for: 5m
        labels:
          severity: warning
          service: celery
        annotations:
          summary: "Celery worker is down"
          description: "No Celery workers are online"

      - alert: CeleryHighQueueLength
        expr: flower_queue_length > 1000
        for: 10m
        labels:
          severity: warning
          service: celery
        annotations:
          summary: "Celery queue length is high"
          description: "Celery queue has {{ $value }} pending tasks"

  - name: infrastructure
    interval: 30s
    rules:
      # System alerts
      - alert: HighCPUUsage
        expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 10m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is above 80% (current value: {{ $value }}%)"

      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
        for: 10m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is above 85% (current value: {{ $value }}%)"

      - alert: DiskSpaceLow
        expr: (1 - (node_filesystem_avail_bytes{fstype!~"tmpfs|fuse.lxcfs"} / node_filesystem_size_bytes)) * 100 > 80
        for: 10m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "Disk space is running low"
          description: "Disk usage is above 80% on {{ $labels.device }} (current value: {{ $value }}%)"