apiVersion: v1
kind: ConfigMap
metadata:
  name: taskflow-config
  namespace: taskflow
data:
  ENVIRONMENT: "production"
  DEBUG: "false"
  # Frontend configuration
  NEXT_PUBLIC_API_URL: "https://api.taskflow.ai"
  NEXT_PUBLIC_WS_URL: "wss://api.taskflow.ai"
  # Backend configuration
  CORS_ORIGINS: "https://taskflow.ai,https://www.taskflow.ai"
  # Redis configuration
  REDIS_DB: "0"
  # Celery configuration
  CELERY_BROKER_DB: "1"
  CELERY_RESULT_DB: "2"