apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: taskflow

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres.yaml
  - redis.yaml
  - backend.yaml
  - frontend.yaml
  - celery.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: taskflow
  app.kubernetes.io/instance: production
  app.kubernetes.io/component: webapp
  app.kubernetes.io/part-of: taskflow-ai

images:
  - name: ghcr.io/yourusername/taskflow-ai-backend
    newTag: latest
  - name: ghcr.io/yourusername/taskflow-ai-frontend
    newTag: latest