import type { HomePageProduct, HomePageCategory } from '@/types/home-page';
import { createProductId, createImageURL, createSlug, createCategoryId } from '@/types';

// Demo products for immediate display
export const demoProducts: HomePageProduct[] = [
  {
    id: createProductId('oversized-tee-black'),
    name: 'OVERSIZED LOGO TEE - BLACK',
    price: '€45.00',
    originalPrice: '€65.00',
    image: createImageURL('https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&h=1000&fit=crop&q=80'),
    slug: createSlug('oversized-logo-tee-black'),
    isNew: true,
    colors: 3,
    description: 'Premium cotton oversized tee with embroidered logo',
    sku: 'SKU-TEE-001' as any,
    variants: [],
    variantId: 'variant_tee_black',
  },
  {
    id: createProductId('cargo-pants-olive'),
    name: 'TACTICAL CARGO PANTS',
    price: '€120.00',
    image: createImageURL('https://images.unsplash.com/photo-1542272604-787c3835535d?w=800&h=1000&fit=crop&q=80'),
    slug: createSlug('tactical-cargo-pants'),
    isNew: false,
    colors: 2,
    description: 'Heavy-duty cargo pants with multiple pockets',
    sku: 'SKU-PANTS-001' as any,
    variants: [],
    variantId: 'variant_cargo_olive',
  },
  {
    id: createProductId('strike-runner-v2'),
    name: 'STRIKE RUNNER V2',
    price: '€180.00',
    originalPrice: '€220.00',
    image: createImageURL('https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&h=1000&fit=crop&q=80'),
    slug: createSlug('strike-runner-v2'),
    isNew: true,
    colors: 4,
    description: 'Limited edition sneakers with cushioned sole',
    sku: 'SKU-SHOE-001' as any,
    variants: [],
    variantId: 'variant_runner_v2',
  },
  {
    id: createProductId('essential-hoodie'),
    name: 'ESSENTIAL HOODIE',
    price: '€85.00',
    image: createImageURL('https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800&h=1000&fit=crop&q=80'),
    slug: createSlug('essential-hoodie'),
    isNew: false,
    colors: 5,
    description: 'Classic heavyweight hoodie with kangaroo pocket',
    sku: 'SKU-HOOD-001' as any,
    variants: [],
    variantId: 'variant_hoodie_black',
  },
  {
    id: createProductId('tech-jacket'),
    name: 'TECH WINDBREAKER',
    price: '€150.00',
    image: createImageURL('https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800&h=1000&fit=crop&q=80'),
    slug: createSlug('tech-windbreaker'),
    isNew: true,
    colors: 2,
    description: 'Water-resistant technical jacket',
    sku: 'SKU-JACK-001' as any,
    variants: [],
    variantId: 'variant_jacket_tech',
  },
  {
    id: createProductId('strike-cap'),
    name: 'STRIKE CAP',
    price: '€35.00',
    image: createImageURL('https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=800&h=1000&fit=crop&q=80'),
    slug: createSlug('strike-cap'),
    isNew: false,
    colors: 3,
    description: 'Adjustable cap with embroidered logo',
    sku: 'SKU-CAP-001' as any,
    variants: [],
    variantId: 'variant_cap_black',
  },
  {
    id: createProductId('utility-vest'),
    name: 'UTILITY VEST',
    price: '€95.00',
    originalPrice: '€125.00',
    image: createImageURL('https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&h=1000&fit=crop&q=80'),
    slug: createSlug('utility-vest'),
    isNew: false,
    colors: 2,
    description: 'Multi-pocket utility vest',
    sku: 'SKU-VEST-001' as any,
    variants: [],
    variantId: 'variant_vest_black',
  },
  {
    id: createProductId('track-pants'),
    name: 'TRACK PANTS',
    price: '€75.00',
    image: createImageURL('https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=800&h=1000&fit=crop&q=80'),
    slug: createSlug('track-pants'),
    isNew: false,
    colors: 3,
    description: 'Comfortable track pants with side stripes',
    sku: 'SKU-TRACK-001' as any,
    variants: [],
    variantId: 'variant_track_black',
  },
];

// Demo categories with better images
export const demoCategories: HomePageCategory[] = [
  {
    id: createCategoryId('new-arrivals'),
    name: 'NEW ARRIVALS',
    count: 24,
    image: createImageURL('https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800&h=800&fit=crop&q=80'),
    slug: createSlug('new-arrivals'),
  },
  {
    id: createCategoryId('streetwear'),
    name: 'STREETWEAR',
    count: 48,
    image: createImageURL('https://images.unsplash.com/photo-1523381210434-271e8be1f52b?w=800&h=800&fit=crop&q=80'),
    slug: createSlug('streetwear'),
  },
  {
    id: createCategoryId('footwear'),
    name: 'FOOTWEAR',
    count: 32,
    image: createImageURL('https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800&h=800&fit=crop&q=80'),
    slug: createSlug('footwear'),
  },
  {
    id: createCategoryId('accessories'),
    name: 'ACCESSORIES',
    count: 16,
    image: createImageURL('https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800&h=800&fit=crop&q=80'),
    slug: createSlug('accessories'),
  },
];