groups:
  - name: taskflow_alerts
    interval: 30s
    rules:
      # Service availability alerts
      - alert: ServiceDown
        expr: up == 0
        for: 2m
        labels:
          severity: critical
          team: devops
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "{{ $labels.job }} on {{ $labels.instance }} has been down for more than 2 minutes."

      # Backend API alerts
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.05
        for: 5m
        labels:
          severity: warning
          team: backend
        annotations:
          summary: "High error rate on {{ $labels.job }}"
          description: "Error rate is {{ $value | humanizePercentage }} for {{ $labels.job }}"

      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: warning
          team: backend
        annotations:
          summary: "High response time on {{ $labels.job }}"
          description: "95th percentile response time is {{ $value }}s for {{ $labels.job }}"

      # Database alerts
      - alert: DatabaseConnectionPoolExhausted
        expr: database_connection_pool_used / database_connection_pool_size > 0.9
        for: 5m
        labels:
          severity: warning
          team: backend
        annotations:
          summary: "Database connection pool nearly exhausted"
          description: "Database connection pool is {{ $value | humanizePercentage }} full"

      - alert: DatabaseDown
        expr: up{job="postgresql"} == 0
        for: 1m
        labels:
          severity: critical
          team: devops
        annotations:
          summary: "PostgreSQL database is down"
          description: "PostgreSQL has been down for more than 1 minute"

      # Redis alerts
      - alert: RedisDown
        expr: up{job="redis"} == 0
        for: 1m
        labels:
          severity: critical
          team: devops
        annotations:
          summary: "Redis is down"
          description: "Redis has been down for more than 1 minute"

      - alert: RedisHighMemoryUsage
        expr: redis_used_memory_bytes / (1024 * 1024 * 1024) > 0.5
        for: 5m
        labels:
          severity: warning
          team: devops
        annotations:
          summary: "Redis memory usage is high"
          description: "Redis is using {{ $value | humanize }}GB of memory"

      # System resource alerts
      - alert: HighCPUUsage
        expr: system_cpu_usage_percent > 80
        for: 5m
        labels:
          severity: warning
          team: devops
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is {{ $value }}% on {{ $labels.instance }}"

      - alert: HighMemoryUsage
        expr: system_memory_usage_percent > 85
        for: 5m
        labels:
          severity: warning
          team: devops
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is {{ $value }}% on {{ $labels.instance }}"

      - alert: DiskSpaceLow
        expr: system_disk_usage_percent > 80
        for: 5m
        labels:
          severity: warning
          team: devops
        annotations:
          summary: "Low disk space"
          description: "Disk usage is {{ $value }}% on {{ $labels.instance }}"

      # Container alerts
      - alert: ContainerRestarting
        expr: rate(container_restart_count[5m]) > 0
        for: 5m
        labels:
          severity: warning
          team: devops
        annotations:
          summary: "Container {{ $labels.container_name }} is restarting"
          description: "Container {{ $labels.container_name }} has restarted {{ $value }} times in the last 5 minutes"

      # Celery alerts
      - alert: CeleryWorkerDown
        expr: up{job="taskflow-celery"} == 0
        for: 2m
        labels:
          severity: critical
          team: backend
        annotations:
          summary: "Celery worker is down"
          description: "Celery worker has been down for more than 2 minutes"

      - alert: HighTaskFailureRate
        expr: rate(tasks_total{status="failed"}[5m]) / rate(tasks_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
          team: backend
        annotations:
          summary: "High task failure rate"
          description: "Task failure rate is {{ $value | humanizePercentage }}"

      # SSL certificate expiry
      - alert: SSLCertificateExpiringSoon
        expr: ssl_cert_expiry_days < 30
        for: 1h
        labels:
          severity: warning
          team: devops
        annotations:
          summary: "SSL certificate expiring soon"
          description: "SSL certificate for {{ $labels.domain }} expires in {{ $value }} days"

      - alert: SSLCertificateExpiryCritical
        expr: ssl_cert_expiry_days < 7
        for: 1h
        labels:
          severity: critical
          team: devops
        annotations:
          summary: "SSL certificate expiring critically soon"
          description: "SSL certificate for {{ $labels.domain }} expires in {{ $value }} days!"