[build]
builder = "NIXPACKS"
buildCommand = "pnpm install --frozen-lockfile --production=false && NODE_OPTIONS='--max-old-space-size=8192' pnpm run build"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs", "pnpm", "python3"]

[deploy]
startCommand = "npx medusa db:migrate && pnpm run start:prod"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
# Production-specific configurations
PORT = 9000
NODE_ENV = "production"
LOG_LEVEL = "warn"
ENABLE_PERFORMANCE_MONITORING = "true"
ENABLE_SECURITY_HEADERS = "true"
ENABLE_RATE_LIMITING = "true"
ENABLE_COMPRESSION = "true"
FORCE_HTTPS = "true"

# Resource limits
MEMORY_LIMIT = "2GB"
CPU_LIMIT = "2"