[build]
builder = "NIXPACKS"
buildCommand = """
  pnpm install --frozen-lockfile --production=false && \
  NODE_OPTIONS='--max-old-space-size=8192' pnpm run build && \
  npx medusa build --admin-only
"""

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs", "pnpm", "python3", "postgresql"]

[deploy]
startCommand = """
  npx medusa db:migrate && \
  node scripts/health-check-server.js & \
  NODE_OPTIONS='--max-old-space-size=4096' pnpm run start:prod
"""
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
numReplicas = 2
region = "us-west1"

[environments.production]
# Core Configuration
PORT = 9000
NODE_ENV = "production"
LOG_LEVEL = "warn"
ENABLE_PERFORMANCE_MONITORING = "true"
ENABLE_SECURITY_HEADERS = "true"
ENABLE_RATE_LIMITING = "true"
ENABLE_COMPRESSION = "true"
FORCE_HTTPS = "true"

# Resource Configuration
MEMORY_LIMIT = "4GB"
CPU_LIMIT = "4"
MIN_INSTANCES = 2
MAX_INSTANCES = 10

# Health Check Configuration
HEALTH_CHECK_INTERVAL = 30000
HEALTH_CHECK_TIMEOUT = 30000
HEALTH_CHECK_RETRIES = 3

# Database Pool Configuration
DATABASE_POOL_MIN = 10
DATABASE_POOL_MAX = 50
DATABASE_IDLE_TIMEOUT = 30000
DATABASE_CONNECTION_TIMEOUT = 20000

# Redis Configuration
REDIS_POOL_SIZE = 50
REDIS_CONNECTION_TIMEOUT = 5000
REDIS_COMMAND_TIMEOUT = 5000

# Worker Configuration
WORKER_CONCURRENCY = 10
JOB_RETRY_LIMIT = 3
JOB_RETRY_DELAY = 60000

# Monitoring
ENABLE_APM = "true"
ENABLE_TRACING = "true"
TRACE_SAMPLE_RATE = 0.1
ENABLE_METRICS = "true"
METRICS_INTERVAL = 60000

[scaling]
minInstances = 2
maxInstances = 10
targetCPU = 70
targetMemory = 80
scaleDownDelay = 300
scaleUpDelay = 60

[services.database]
plan = "production"
enableBackups = true
backupSchedule = "0 */6 * * *"
backupRetention = 30
enablePointInTimeRecovery = true
enableReadReplicas = true
readReplicaCount = 2

[services.redis]
plan = "production"
enablePersistence = true
maxMemoryPolicy = "allkeys-lru"
enableCluster = true

[services.monitoring]
enableDatadog = true
enableSentry = true
enableNewRelic = true
enableCustomMetrics = true