[build]
builder = "NIXPACKS"
buildCommand = "pnpm install --frozen-lockfile && NODE_OPTIONS='--max-old-space-size=4096' pnpm run build"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs", "pnpm", "python3"]

[deploy]
startCommand = "npx medusa db:migrate && pnpm run start"
healthcheckPath = "/health"
healthcheckTimeout = 180
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[environments.staging]
# Staging-specific configurations
PORT = 9000
NODE_ENV = "production"
LOG_LEVEL = "info"
ENABLE_PERFORMANCE_MONITORING = "true"