apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: taskflow

bases:
  - ../../base

patchesStrategicMerge:
  - replica-patch.yaml
  - resource-patch.yaml

configMapGenerator:
  - name: taskflow-config
    behavior: merge
    literals:
      - ENVIRONMENT=production
      - DEBUG=false

secretGenerator:
  - name: taskflow-secrets
    behavior: replace
    envs:
      - secrets.env

replicas:
  - name: backend
    count: 5
  - name: frontend
    count: 5
  - name: celery-worker
    count: 3

images:
  - name: ghcr.io/yourusername/taskflow-ai-backend
    newTag: v1.0.0
  - name: ghcr.io/yourusername/taskflow-ai-frontend
    newTag: v1.0.0