apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: taskflow
spec:
  replicas: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: taskflow
spec:
  replicas: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  namespace: taskflow
spec:
  replicas: 3