/**
 * Central export for all Shopify GraphQL queries
 */

// Product queries
export {
  PRODUCT_FRAGMENT,
  GET_PRODUCTS_QUERY,
  GET_PRODUCT_BY_HANDLE_QUERY,
  GET_PRODUCT_BY_ID_QUERY,
  SEARCH_PRODUCTS_QUERY,
  GET_PRODUCT_RECOMMENDATIONS_QUERY,
  GET_PRODUCTS_BY_COLLECTION_QUERY,
} from './product';

// Collection queries
export {
  COLLECTION_FRAGMENT,
  PRODUCT_IN_COLLECTION_FRAGMENT,
  GET_COLLECTIONS_QUERY,
  GET_COLLECTION_BY_HANDLE_QUERY,
  GET_COLLECTION_PRODUCTS_QUERY,
  GET_FEATURED_COLLECTIONS_QUERY,
} from './collection';

// Market queries
export {
  GET_MARKETS_QUERY,
  GET_SHOP_LOCALIZATION_QUERY,
  GET_PRODUCT_TRANSLATIONS_QUERY,
  GET_COLLECTION_TRANSLATIONS_QUERY,
  GET_SHOP_POLICIES_QUERY,
  GET_MENU_TRANSLATIONS_QUERY,
  CHECK_PRODUCT_AVAILABILITY_QUERY,
  GET_MARKET_PRICING_QUERY,
} from './markets';

// Cart queries (existing)
export * from './checkout';